version: '3.7'

services:

  cicd:
    container_name: jenkins
    restart: unless-stopped:0
    build:
      context: ./
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - cicd

networks:
  cicd:
    driver: bridge
